In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ACER\Downloads\Ecommerce_Consumer_Behavior_Analysis_Data.csv")

In [2]:
df.shape

(1000, 28)

In [3]:
df.head()

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,NaN,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 28 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Customer_ID                            1000 non-null   object
 1   Age                                    1000 non-null   int64
 2   Gender                                 1000 non-null   object
 3   Income_Level                           1000 non-null   object
 4   Marital_Status                         1000 non-null   object
 5   Education_Level                        1000 non-null   object
 6   Occupation                             1000 non-null   object
 7   Location                               1000 non-null   object
 8   Purchase_Category                      1000 non-null   object
 9   Purchase_Amount                        1000 non-null   object
 10  Frequency_of_Purchase                  1000 non-null   int64
 11  Purchase_Channel                       1000 non-null   object
 12  Brand_Loyalty                          1000 non-null   int64
 13  Product_Rating                         1000 non-null   int64
 14  Time_Spent_on_Product_Research(hours)  1000 non-null   float64
 15  Social_Media_Influence                 753 non-null    object
 16  Discount_Sensitivity                   1000 non-null   object
 17  Return_Rate                            1000 non-null   int64
 18  Customer_Satisfaction                  1000 non-null   int64
 19  Engagement_with_Ads                    744 non-null    object
 20  Device_Used_for_Shopping               1000 non-null   object
 21  Payment_Method                         1000 non-null   object
 22  Time_of_Purchase                       1000 non-null   object
 23  Discount_Used                          1000 non-null   bool
 24  Customer_Loyalty_Program_Member        1000 non-null   bool
 25  Purchase_Intent                        1000 non-null   object
 26  Shipping_Preference                    1000 non-null   object
 27  Time_to_Decision                       1000 non-null   int64
dtypes: bool(2), float64(1), int64(7), object(18)
memory usage: 205.2+ KB

In [11]:
df.describe(include = "all")

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
count,1000,1000.000000,1000,1000,1000,1000,1000,1000,1000,1000,...,1000.000000,744,1000,1000,1000,1000,1000,1000,1000,1000.000000
unique,1000,NaN,8,2,4,3,2,969,24,989,...,NaN,3,3,5,344,2,2,4,3,NaN
top,37-611-6911,NaN,Female,High,Widowed,Bachelor's,High,Oslo,Electronics,$178.04,...,NaN,High,Desktop,PayPal,3/3/2024,True,False,Need-based,No Preference,NaN
freq,1,NaN,452,515,260,341,517,4,54,2,...,NaN,270,350,219,8,521,509,256,372,NaN
mean,NaN,34.304000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.399000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.547000
std,NaN,9.353238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.868454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.035849
min,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,NaN,26.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
50%,NaN,34.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000
75%,NaN,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.000000
max,NaN,50.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000

In [12]:
df.isnull().sum()

Customer_ID                                0
Age                                        0
Gender                                     0
Income_Level                               0
Marital_Status                             0
Education_Level                            0
Occupation                                 0
Location                                   0
Purchase_Category                          0
Purchase_Amount                            0
Frequency_of_Purchase                      0
Purchase_Channel                           0
Brand_Loyalty                              0
Product_Rating                             0
Time_Spent_on_Product_Research(hours)      0
Social_Media_Influence                   247
Discount_Sensitivity                       0
Return_Rate                                0
Customer_Satisfaction                      0
Engagement_with_Ads                      256
Device_Used_for_Shopping                   0
Payment_Method                             0
Time_of_Purchase                           0
Discount_Used                              0
Customer_Loyalty_Program_Member            0
Purchase_Intent                            0
Shipping_Preference                        0
Time_to_Decision                           0
dtype: int64

In [13]:
# Replace with the most frequent value (Mode)
df['Engagement_with_Ads'] = df['Engagement_with_Ads'].fillna(df['Engagement_with_Ads'].mode()[0])
df['Social_Media_Influence'] = df['Social_Media_Influence'].fillna(df['Social_Media_Influence'].mode()[0])

In [15]:
df.isnull().sum()

Customer_ID                              0
Age                                      0
Gender                                   0
Income_Level                             0
Marital_Status                           0
Education_Level                          0
Occupation                               0
Location                                 0
Purchase_Category                        0
Purchase_Amount                          0
Frequency_of_Purchase                    0
Purchase_Channel                         0
Brand_Loyalty                            0
Product_Rating                           0
Time_Spent_on_Product_Research(hours)    0
Social_Media_Influence                   0
Discount_Sensitivity                     0
Return_Rate                              0
Customer_Satisfaction                    0
Engagement_with_Ads                      0
Device_Used_for_Shopping                 0
Payment_Method                           0
Time_of_Purchase                         0
Discount_Used                            0
Customer_Loyalty_Program_Member          0
Purchase_Intent                          0
Shipping_Preference                      0
Time_to_Decision                         0
dtype: int64

In [17]:
df.columns = df.columns.str.lower()

In [20]:
df.columns

Index(['customer_id', 'age', 'gender', 'income_level', 'marital_status',
       'education_level', 'occupation', 'location', 'purchase_category',
       'purchase_amount', 'frequency_of_purchase', 'purchase_channel',
       'brand_loyalty', 'product_rating',
       'time_spent_on_product_research(hours)', 'social_media_influence',
       'discount_sensitivity', 'return_rate', 'customer_satisfaction',
       'engagement_with_ads', 'device_used_for_shopping', 'payment_method',
       'time_of_purchase', 'discount_used', 'customer_loyalty_program_member',
       'purchase_intent', 'shipping_preference', 'time_to_decision'],
      dtype='object')

In [24]:
# To create an age_group column
bins = [0, 18, 35, 60, 100]
labels = ['Young', 'Adult', 'Middle Aged', 'Senior']


df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [23]:
print(df[['age', 'age_group']].head(10))

   age    age_group
0   22        Adult
1   49  Middle Aged
2   24        Adult
3   29        Adult
4   33        Adult
5   45  Middle Aged
6   21        Adult
7   39  Middle Aged
8   24        Adult
9   25        Adult

In [26]:
# To create a column called purchase efficiency
# 1. Remove '$' and ',' then convert to float
df['purchase_amount'] = df['purchase_amount'].replace('[\$,]', '', regex=True).astype(float)

# 2. Now run the division
df['purchase_efficiency'] = df['purchase_amount'] / df['time_to_decision']

# 3. View the result
print(df[['purchase_amount', 'time_to_decision', 'purchase_efficiency']].head())

   purchase_amount  time_to_decision  purchase_efficiency
0           333.80                 2           166.900000
1           222.22                 6            37.036667
2           426.22                 3           142.073333
3           101.31                10            10.131000
4           211.70                 4            52.925000

In [27]:
# Marks users who are members AND gave a rating of 8 or higher
df['is_vip'] = (df['customer_loyalty_program_member'] == True) & (df['product_rating'] >= 8)

In [28]:
# Mapping text to numbers to create a combined score
influence_map = {'Low': 1, 'Middle': 2, 'High': 3}
df['digital_score'] = df['social_media_influence'].map(influence_map) + df['engagement_with_ads'].map(influence_map)

In [31]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.columns

Index(['customer_id', 'age', 'gender', 'income_level', 'marital_status',
       'education_level', 'occupation', 'location', 'purchase_category',
       'purchase_amount', 'frequency_of_purchase', 'purchase_channel',
       'brand_loyalty', 'product_rating',
       'time_spent_on_product_research(hours)', 'social_media_influence',
       'discount_sensitivity', 'return_rate', 'customer_satisfaction',
       'engagement_with_ads', 'device_used_for_shopping', 'payment_method',
       'time_of_purchase', 'discount_used', 'customer_loyalty_program_member',
       'purchase_intent', 'shipping_preference', 'time_to_decision',
       'age_group', 'purchase_efficiency', 'is_vip', 'digital_score'],
      dtype='object')

In [39]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

# 1. Encode the password to handle the '@' symbol correctly
password = urllib.parse.quote_plus("sudip@123")

# 2. Build the connection string using the encoded password
connection_string = f'mysql+mysqlconnector://root:{password}@localhost/consumer_behavior'

try:
    engine = create_engine(connection_string)
    # 3. Test the connection
    with engine.connect() as conn:
        print("Connection Successful! Your notebook is now linked to MySQL.")
except Exception as e:
    print(f"Connection Failed: {e}")

Connection Failed: No module named 'mysql'

In [4]:
!pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in c:\users\acer\appdata\roaming\python\python313\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in c:\users\acer\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [5]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [6]:
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='sudip@123',
    database='consumer_behavior'
)

print("Connected successfully")

Connected successfully

In [12]:
engine = create_engine("mysql+pymysql://root:sudip%40123@localhost/consumer_behavior")

In [13]:
df.to_sql(
    name='ecommerce_data',   # table name in MySQL
    con=engine,
    if_exists='replace',     # replace if table exists
    index=False
)

print("Data uploaded successfully")

Data uploaded successfully

In [14]:
df_sql = pd.read_sql("SELECT * FROM ecommerce_data LIMIT 5", engine)
df_sql

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,None,Tablet,Credit Card,3/1/2024,1,0,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,1,0,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,1,1,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,None,Smartphone,Other,10/4/2024,1,1,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,None,Smartphone,Debit Card,1/30/2024,0,0,Wants-based,No Preference,4

In [17]:
df.dtypes

Customer_ID                               object
Age                                        int64
Gender                                    object
Income_Level                              object
Marital_Status                            object
Education_Level                           object
Occupation                                object
Location                                  object
Purchase_Category                         object
Purchase_Amount                           object
Frequency_of_Purchase                      int64
Purchase_Channel                          object
Brand_Loyalty                              int64
Product_Rating                             int64
Time_Spent_on_Product_Research(hours)    float64
Social_Media_Influence                    object
Discount_Sensitivity                      object
Return_Rate                                int64
Customer_Satisfaction                      int64
Engagement_with_Ads                       object
Device_Used_for_Shopping                  object
Payment_Method                            object
Time_of_Purchase                          object
Discount_Used                               bool
Customer_Loyalty_Program_Member             bool
Purchase_Intent                           object
Shipping_Preference                       object
Time_to_Decision                           int64
dtype: object